name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Configure GPG Key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:     
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      -
        name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
